//! This pass binds only item names.
//! Items are: functions, structs, enums, and methods.
//! Basically everything that should be usable above the declaration.

const std = @import("std");

const common = @import("../common.zig");
const ast = @import("../parse/ast.zig");
const visitor = @import("../visitor.zig");
const Metadata = @import("Metadata.zig");

const Visitor = visitor.Visitor(ast.Node, @This(), std.mem.Allocator.Error, void{});
pub usingnamespace Visitor;

metadata: *Metadata,
current_nodeid: usize = 0, // This will be modified by visitor.

const Self = @This();
const LOG = std.log.scoped(.item_name_binding_pass);

// TODO: Imports, but they must be first made into modules by ImportResolutionPass.
pub fn visitFunctionDef(self: *Self, tree: *const ast.Tree, span: common.Span, def: ast.FunctionDef, visitee: anytype) !void {
    _ = visitee;
    _ = span;

    // Add function name to global scope.
    var global = self.metadata.getScope(Metadata.GLOBAL);
    // Safety: Name node must have been generated by parser.
    const fn_name = tree.getNodeUnsafe(def.name).kind.identifier;
    try global.known_names.put(fn_name, self.current_nodeid);
    LOG.debug("Bound name '{s}' to function definition #{d}.", .{ fn_name, self.current_nodeid });

    // Generate and bind new scope for function body.
    const fn_scope = try self.metadata.pushScope();
    self.metadata.references[self.current_nodeid] = fn_scope;

    // We do not need to travel parameters in this pass.
    try self.accept(tree, def.body);

    _ = self.metadata.popScope();
}

pub fn visitNativeFunctionDecl(self: *Self, tree: *const ast.Tree, span: common.Span, decl: ast.NativeFunctionDecl, visitee: anytype) !void {
    _ = visitee;
    _ = span;

    // Add function name to global scope.
    var global = self.metadata.getScope(Metadata.GLOBAL);
    // Safety: Name node must have been generated by parser.
    const fn_name = tree.getNodeUnsafe(decl.name).kind.identifier;
    try global.known_names.put(fn_name, self.current_nodeid);
    LOG.debug("Bound name '{s}' to native function declaration #{d}.", .{ fn_name, self.current_nodeid });
}

pub fn visitStructDecl(self: *Self, tree: *const ast.Tree, span: common.Span, decl: ast.StructDecl, visitee: anytype) !void {
    _ = visitee;
    _ = span;

    // Add struct name to global scope.
    var global = self.metadata.getScope(Metadata.GLOBAL);
    // Safety: Name node must have been generated by parser.
    const struct_name = tree.getNodeUnsafe(decl.name).kind.identifier;
    try global.known_names.put(struct_name, self.current_nodeid);
    LOG.debug("Bound name '{s}' to structure #{d}.", .{ struct_name, self.current_nodeid });

    // Generate and bind new scope for method declarations (only static).
    const struct_scope = try self.metadata.pushScope();
    self.metadata.references[self.current_nodeid] = struct_scope;

    // We do not need to travel fields in this pass.
    for (decl.decls) |d| {
        try self.accept(tree, d);
    }

    _ = self.metadata.popScope();
}

pub fn visitEnumDecl(self: *Self, tree: *const ast.Tree, span: common.Span, decl: ast.EnumDecl, visitee: anytype) !void {
    _ = visitee;
    _ = span;

    // Add struct name to global scope.
    var global = self.metadata.getScope(Metadata.GLOBAL);
    // Safety: Name node must have been generated by parser.
    const enum_name = tree.getNodeUnsafe(decl.name).kind.identifier;
    try global.known_names.put(enum_name, self.current_nodeid);
    LOG.debug("Bound name '{s}' to enum #{d}.", .{ enum_name, self.current_nodeid });

    // Generate and bind new scope for method declarations (only static).
    const enum_scope = try self.metadata.pushScope();
    self.metadata.references[self.current_nodeid] = enum_scope;

    // We do not need to travel fields in this pass.
    for (decl.decls) |d| {
        try self.accept(tree, d);
    }

    _ = self.metadata.popScope();
}
